#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @handle")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get screen name
    screen_name = sys.argv[1].strip('@')

    if screen_name is None:
        sys.exit("Sorry this Screen name is invalid")

    # get screen_name's last 50 tweets
    tweets = helpers.get_user_timeline(screen_name, 50)

    # if function fails, return error message
    if tweets is None:
        sys.exit("Sorry no tweets to show ")

    # analyze tweets and score
    for tweet in tweets:
        score = analyzer.analyze(sys.argv[1])
        if score > 0.0:
            print(colored(f"{score} {tweets}", "green")
        elif score < 0.0:
            print(colored(f"{score} {tweets}", "red")
        else:
            print(colored(f"{score} {tweet}", "yellow")
if __name__ == "__main__":
    main()
